// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const classNames: typeof import('classnames')['default']
  const toast: typeof import('react-hot-toast')['toast']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useInfiniteQuery: typeof import('react-query')['useInfiniteQuery']
  const useMemo: typeof import('react')['useMemo']
  const useMutation: typeof import('react-query')['useMutation']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useParams: typeof import('react-router-dom')['useParams']
  const useQuery: typeof import('react-query')['useQuery']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useSnapshot: typeof import('valtio')['useSnapshot']
  const useState: typeof import('react')['useState']
}
export {}
