export enum APIs {
  UserPlaylist = 'user/playlist',
  UserAccount = 'user/account',
  Personalized = 'personalized',
  RecommendResource = 'recommend/resource',
  Likelist = 'likelist',
  SongDetail = 'song/detail',
  SongUrl = 'song/url',
  Album = 'album',
  PlaylistDetail = 'playlist/detail',
  Artists = 'artists',
  ArtistAlbum = 'artist/album',
  Lyric = 'lyric',
  CoverColor = 'cover_color',
}
