export enum IpcChannels {
  ClearAPICache = 'clear-api-cache',
  Minimize = 'minimize',
  MaximizeOrUnmaximize = 'maximize-or-unmaximize',
  Close = 'close',
  IsMaximized = 'is-maximized',
  GetApiCacheSync = 'get-api-cache-sync',
  DevDbExportJson = 'dev-db-export-json',
  CacheCoverColor = 'cache-cover-color',
  SetTrayTooltip = 'set-tray-tooltip',
  SetTrayPlayState = 'set-tray-play-state',
  SetTrayLikeState = 'set-tray-like-state',
  // 准备三个播放相关channel, 为 mpris预留接口
  Play = 'play',
  Pause = 'pause',
  PlayOrPause = 'play-or-pause',
  Next = 'next',
  Previous = 'previous',
  Like = 'like',
  Repeat = 'repeat',
}
