name: Build

permissions:
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install deps
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Install Linux system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y rpm libarchive-tools libopenjp2-tools

      - name: Install @unblockneteasemusic/rust-napi native deps (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:npm_config_ignore_platform = 'true'
          $env:npm_config_ignore_engines = 'true'
          yarn add --ignore-platform --ignore-engines --non-interactive --no-lockfile --exact @unblockneteasemusic/rust-napi-win32-x64-msvc

      - name: Install @unblockneteasemusic/rust-napi native deps (macOS)
        if: runner.os == 'macOS'
        run: |
          yarn add --ignore-platform --ignore-engines --non-interactive --no-lockfile --exact \
            @unblockneteasemusic/rust-napi-darwin-x64 \
            @unblockneteasemusic/rust-napi-darwin-arm64 \
            dmg-license

      - name: Install @unblockneteasemusic/rust-napi native deps (Linux)
        if: runner.os == 'Linux'
        run: |
          yarn add --ignore-platform --ignore-engines --non-interactive --no-lockfile --exact \
            @unblockneteasemusic/rust-napi-linux-x64-gnu \
            @unblockneteasemusic/rust-napi-linux-arm64-gnu

      - name: Build Electron app
        run: yarn electron:build --publish never
        env:
          VUE_APP_NETEASE_API_URL: /api
          VUE_APP_ELECTRON_API_URL: /api
          VUE_APP_LASTFM_API_KEY: 09c55292403d961aa517ff7f5e8a3d9c
          VUE_APP_LASTFM_API_SHARED_SECRET: 307c9fda32b3904e53654baff215cb67
          GH_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v4
        if: runner.os == 'macOS'
        with:
          name: YesPlayMusic-mac
          path: dist_electron/*.dmg
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: YesPlayMusic-win
          path: dist_electron/*Setup*.exe
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: YesPlayMusic-linux
          path: dist_electron/*.AppImage
          if-no-files-found: ignore